apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: tkg-gitops-demo
  namespace: default
spec:
  bastion:
    enabled: false
  network:
    cni:
      cniIngressRules:
      - description: antrea1
        fromPort: 10349
        protocol: tcp
        toPort: 10349
      - description: genev
        fromPort: 6081
        protocol: udp
        toPort: 6081
      - description: kapp-controller
        fromPort: 10100
        protocol: tcp
        toPort: 10100
    subnets:
    - availabilityZone: eu-west-1a
      cidrBlock: 10.0.16.0/20
      id: ""
    - availabilityZone: eu-west-1a
      cidrBlock: 10.0.0.0/20
      id: ""
      isPublic: true
    vpc:
      cidrBlock: 10.0.0.0/16
      id: ""
  region: eu-west-1
  sshKeyName: aws
